# 数据库配置
spring:
  cache:
    redis:
      time-to-live: 3600s
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/exerciseSystem
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/exercise_system_test?characterEncoding=UTF8&serverTimeZone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: dreamxzj
      druid:
        initial-size: 5

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
    - classpath*:com/**/mappers/*.xml