spring:
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  profiles:
    active: "local"
    #    使用maven里的配置
    #    active: @profile.active@
    group:
      "dev": dev,devDatabase,customize
      "local": local,localDatabase,customize
      "test": testStandard
      "prod": prod,prodDatabase,customize