spring:
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  profiles:
    active: "dev"
#    使用maven里的配置
#    active: @profile.active@
    group:
      "dev": devStandard,devDB,devCustomize
      "test": testStandard
